// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg281-iw0SHq71llzDi0Io8-G2_exUv6s',
    appId: '1:312253455595:web:5a1580321b219e386032ae',
    messagingSenderId: '312253455595',
    projectId: 'e-commerce-app-6ec12',
    authDomain: 'e-commerce-app-6ec12.firebaseapp.com',
    storageBucket: 'e-commerce-app-6ec12.appspot.com',
    measurementId: 'G-0TPVJT01H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq7a_kfD1K1clqghCTpnbGz6GP_NfwFkc',
    appId: '1:312253455595:android:d606c5726c5d99fc6032ae',
    messagingSenderId: '312253455595',
    projectId: 'e-commerce-app-6ec12',
    storageBucket: 'e-commerce-app-6ec12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANVq6dZ6ma88Lqw2xu440gEAdiExJXpw8',
    appId: '1:312253455595:ios:fe8164c37cf173f86032ae',
    messagingSenderId: '312253455595',
    projectId: 'e-commerce-app-6ec12',
    storageBucket: 'e-commerce-app-6ec12.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANVq6dZ6ma88Lqw2xu440gEAdiExJXpw8',
    appId: '1:312253455595:ios:fe8164c37cf173f86032ae',
    messagingSenderId: '312253455595',
    projectId: 'e-commerce-app-6ec12',
    storageBucket: 'e-commerce-app-6ec12.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg281-iw0SHq71llzDi0Io8-G2_exUv6s',
    appId: '1:312253455595:web:bf03d271299f2d2d6032ae',
    messagingSenderId: '312253455595',
    projectId: 'e-commerce-app-6ec12',
    authDomain: 'e-commerce-app-6ec12.firebaseapp.com',
    storageBucket: 'e-commerce-app-6ec12.appspot.com',
    measurementId: 'G-ZLF2HD4H2Z',
  );
}
